// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azmmaruwodokfluvarwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6bW1hcnV3b2Rva2ZsdXZhcndiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODg5OTAsImV4cCI6MjA2Njc2NDk5MH0.WnE8UtYfaV4dYebGFjRHdrG74ERMmuCKoteZsixp62U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);